name: CI
on: push
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get update
    - run: sudo apt-get install -y shellcheck
    - uses: actions/checkout@v2
    - run: shellcheck bin/*
  install:
    runs-on: macos-latest
    env:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
    - uses: actions/checkout@v2
    - run: brew tap alexpyoung/tools
    - run: brew install alexpyoung/tools/packageddataviewer
    - run: brew install alexpyoung/tools/pet
    - run: brew install alexpyoung/tools/protonvpn
