name: CI
on: push
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get update
    - run: sudo apt-get install -y shellcheck
    - uses: actions/checkout@v2
    - run: shellcheck bin/*